"""bot whatsapp ventas: conversaciones, leads e idempotencia

Revision ID: 019426b0cd06
Revises: 22502bd4cbd9
Create Date: 2026-07-16 15:02:49.833150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '019426b0cd06'
down_revision: Union[str, Sequence[str], None] = '22502bd4cbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('collected', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('collect_turns', sa.Integer(), server_default='0', nullable=False),
    sa.Column('handed_off', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_conversations_phone', 'bot_conversations', ['phone'], unique=False)
    op.create_table('bot_inbound_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wamid', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_inbound_events_wamid', 'bot_inbound_events', ['wamid'], unique=True)
    op.create_table('bot_leads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('workers_estimate', sa.String(length=40), nullable=True),
    sa.Column('interest', sa.Text(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['bot_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_leads_conversation_id', 'bot_leads', ['conversation_id'], unique=False)
    op.create_table('bot_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['bot_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_messages_conversation_id', 'bot_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bot_messages_conversation_id', table_name='bot_messages')
    op.drop_table('bot_messages')
    op.drop_index('ix_bot_leads_conversation_id', table_name='bot_leads')
    op.drop_table('bot_leads')
    op.drop_index('ix_bot_inbound_events_wamid', table_name='bot_inbound_events')
    op.drop_table('bot_inbound_events')
    op.drop_index('ix_bot_conversations_phone', table_name='bot_conversations')
    op.drop_table('bot_conversations')
    # ### end Alembic commands ###
