"""phase6 billing: subscriptions + payment_events

Revision ID: 1ac66b2f6de5
Revises: b8d4f0a2c6e1
Create Date: 2026-07-15 13:47:07.848866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ac66b2f6de5'
down_revision: Union[str, Sequence[str], None] = 'b8d4f0a2c6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('flow_customer_id', sa.String(length=100), nullable=True),
    sa.Column('flow_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('flow_plan_id', sa.String(length=100), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('flow_event_type', sa.String(length=50), nullable=False),
    sa.Column('flow_token', sa.String(length=120), nullable=True),
    sa.Column('commerce_order', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_events_flow_token', 'payment_events', ['flow_token'], unique=True)
    op.create_index('ix_payment_events_org_id', 'payment_events', ['org_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: toda organización existente nace en el plan free (status active).
    op.execute(
        """
        INSERT INTO subscriptions (id, org_id, plan, status)
        SELECT gen_random_uuid(), o.id, 'free', 'active'
        FROM organizations o
        WHERE NOT EXISTS (
            SELECT 1 FROM subscriptions s WHERE s.org_id = o.id
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_events_org_id', table_name='payment_events')
    op.drop_index('ix_payment_events_flow_token', table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
