class ErrorCode:
    # Auth
    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    FORBIDDEN = "FORBIDDEN"

    # Organizations
    ORG_NOT_FOUND = "ORG_NOT_FOUND"
    NOT_ORG_MEMBER = "NOT_ORG_MEMBER"
    NOT_ORG_ADMIN = "NOT_ORG_ADMIN"

    # Projects
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"

    # Workers
    WORKER_NOT_FOUND = "WORKER_NOT_FOUND"
    WORKER_DUPLICATE_RUT = "WORKER_DUPLICATE_RUT"
    INVALID_RUT = "INVALID_RUT"

    # Evaluations
    EVALUATION_NOT_FOUND = "EVALUATION_NOT_FOUND"
    EVALUATION_DUPLICATE = "EVALUATION_DUPLICATE"
    EVALUATION_EDIT_WINDOW_EXPIRED = "EVALUATION_EDIT_WINDOW_EXPIRED"

    # Validation
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Server
    INTERNAL_ERROR = "INTERNAL_ERROR"
